### ISSUE TITLE
[11.0] Problem installing this module in a clean database

### ISSUE THREAD

**Issue by SalahAdDin** [guohuadeng/app-odoo#15]
I had to delete my old database because a strong problem with localization files.

After that, i decided recover my database, so, i restarted odoo but i got the next bug:
```bash
 salahaddin@TulipanROG  ~/Proyectos/Works/rotafilo   local-prod ● ?  docker exec -it odoo.web bash                                                                 KILL(-9) ↵  4219  10:31:26
odoo@0879d538d2b2:/$ cat var/log/odoo/openerp-server.log
2018-06-22 07:32:24,342 1 WARNING rotafilo odoo.modules.loading: Transient module states were reset
2018-06-22 07:32:24,394 1 ERROR rotafilo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_modules
    report=report, models_to_check=models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 783, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/res/res.lang.csv
2018-06-22 07:32:24,395 1 CRITICAL rotafilo odoo.service.server: Failed to initialize database `rotafilo`.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 925, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_modules
    report=report, models_to_check=models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 783, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/res/res.lang.csv
2018-06-22 07:32:26,567 14 WARNING rotafilo odoo.modules.loading: Transient module states were reset
2018-06-22 07:32:26,567 14 ERROR rotafilo odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 59, in __new__
    return cls.registries[db_name]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'rotafilo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_modules
    report=report, models_to_check=models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 783, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/res/res.lang.csv
2018-06-22 07:32:26,574 14 ERROR rotafilo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1473, in dispatch
    odoo.registry(db).check_signaling()
  File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 312, in load_modules
    report=report, models_to_check=models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 783, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 193, in file_open
    pathinfo=pathinfo, basename=basename)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 211, in _fileopen
    raise ValueError("Unknown path: %s" % name)
ValueError: Unknown path: /base/res/res.lang.csv
```

I decided to delete this repository's path from addons path and the bug disappeared.

Why?

i think it's because your are not using the best practice for migrate this module to `11.0`.

**Comment by SalahAdDin** [comment]
And yes, after two days, I can confirm this bug.

**Comment by SalahAdDin** [comment]
@guohuadeng

**Comment by SalahAdDin** [comment]
@guohuadeng why did you close this issue?
