### ISSUE TITLE
安裝app_product_type_sequence模組後，無法開立發票

### ISSUE THREAD

**Issue by SmithLin0618** [guohuadeng/app-odoo#17]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 895, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 883, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account/models/account_invoice.py", line 582, in action_invoice_open
    return to_open_invoices.invoice_validate()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account_document/models/account_invoice.py", line 26, in invoice_validate
    """
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5007, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/usr/lib/python2.7/dist-packages/odoo/addons/account_document/models/account_invoice.py", line 26, in <lambda>
    """
AttributeError: 'account.invoice' object has no attribute 'use_documents'

**Comment by guohuadeng** [comment]
10版本不再更新，请移步 
http://www.odoo.com/apps/modules/12.0/app_product_auto_code/
