### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by levin222** [guohuadeng/app-odoo#22]
由于经常直接用git来更新代码，发现你们的git提交上来时常有错误的代码，导致整个系统无法运行，烦请确认没问题再提交。。。
最近11.0 
**app_purchase_report**
app_mrp_bom_location 
这两个都有问题，目前没用到这两个addons，没去核对代码
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 260, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1317, in __call__
    self.load_addons()
  File "/odoo/odoo-server/odoo/http.py", line 1349, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/odoo/odoo-server/odoo/modules/module.py", line 61, in load_module
    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name, ad_paths)
  File "/usr/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'app_purchase_report'

应该是 from. import xxx 和import xxx 这个11.0 特有的问题吧

**Comment by levin222** [comment]
有错误的算是半成品，应该 installable =False 就不会导致系统不能运行吧

**Comment by guohuadeng** [comment]
多谢，10版本插件已经不维护。 新的全部在11和12的分支
