### ISSUE TITLE
Can't install app_module_superbar

### ISSUE THREAD

**Issue by eqms** [guohuadeng/app-odoo#23]
```
Fehler:
Odoo Server Error

Traceback (most recent call last):
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3821, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/dev/gitbase/v12/v12-server/addons/website/models/ir_ui_view.py", line 128, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3735, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/dev/gitbase/v12/v12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/dev/gitbase/v12/v12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3552, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/dev/gitbase/v12/v12-server/odoo/fields.py", line 1097, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/dev/gitbase/v12/v12-server/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3269, in write
    self._write(store_vals)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3413, in _write
    self._validate_fields(vals)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view ir.module.module.list.select definition in app_module_superbar/views/module_views.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dev/gitbase/v12/v12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/dev/gitbase/v12/v12-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/dev/gitbase/v12/v12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/dev/gitbase/v12/v12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dev/gitbase/v12/v12-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/dev/gitbase/v12/v12-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_module.py", line 553, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/dev/gitbase/v12/v12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/dev/gitbase/v12/v12-server/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/dev/gitbase/v12/v12-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/dev/gitbase/v12/v12-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/dev/gitbase/v12/v12-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/dev/gitbase/v12/v12-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3821, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/dev/gitbase/v12/v12-server/addons/website/models/ir_ui_view.py", line 128, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3735, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/home/dev/gitbase/v12/v12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/dev/gitbase/v12/v12-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3552, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/dev/gitbase/v12/v12-server/odoo/fields.py", line 1097, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/dev/gitbase/v12/v12-server/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3269, in write
    self._write(store_vals)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 3413, in _write
    self._validate_fields(vals)
  File "/home/dev/gitbase/v12/v12-server/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/home/dev/gitbase/v12/v12-server/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view ir.module.module.list.select definition in app_module_superbar/views/module_views.xml
None" while parsing /home/dev/gitbase/v12/v12-oca/3rdparty/app_module_superbar/views/module_views.xml:4, near
<record id="view_module_filter_superbar" model="ir.ui.view">
        <field name="name">ir.module.module.list.select</field>
        <field name="model">ir.module.module</field>
        <field name="inherit_id" ref="base.view_module_filter"/>
        <field name="arch" type="xml">
            <xpath expr="//search">
                <superbar view_mode="kanban,tree">
                    <field name="state"/>
                    <field name="category_id" domain="[]" parent_key="parent_id"/>
                    <field name="license"/>
                </superbar>
            </xpath>
        </field>
    </record>
```

**Comment by guohuadeng** [comment]
pls buy "app_web_superbar" app in odoo store.
