### ISSUE TITLE
Can not apply changes, error raised..

### ISSUE THREAD

**Issue by trixocom** [guohuadeng/app-odoo#36]
Odoo 13 CE 20210103, module cloned today.
 This is the error I get when trying to apply changes.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 385, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 365, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-150>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/res_config_settings.py", line 156, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3805, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3965, in _create
    for other, data in zip(others, data_list)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2861, in create
    self.write_batch(record_values, True)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2887, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3435, in write_real
    relation_set(recs._ids, command[2] if command[0] == 6 else ())
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3407, in relation_set
    new_relation[x] = set(ys)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 1073, in __init__
    self._map = OrderedDict((elem, None) for elem in elems)
TypeError: 'NoneType' object is not iterable

**Comment by guohuadeng** [comment]
which apps?

**Comment by trixocom** [comment]
Your app!
I change company name instead of odoo_app and when trying to apply I get
the error.

**Comment by guohuadeng** [comment]
update would fixed.
