### ISSUE TITLE
app_mrp_superbar  V14安装出错：字段"routing_id" 不存在于模型 "mrp.bom"中

### ISSUE THREAD

**Issue by n86431** [guohuadeng/app-odoo#37]
错误:
Odoo Server Error

Traceback (most recent call last):
  File "E:\odoo14\odoo-14.0E\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "E:\odoo14\odoo-14.0E\odoo\tools\convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "E:\odoo14\odoo-14.0E\odoo\models.py", line 4203, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "E:\odoo14\odoo-14.0E\odoo\models.py", line 4132, in _load_records_create
    return self.create(values)
  File "<decorator-gen-43>", line 2, in create
  File "E:\odoo14\odoo-14.0E\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "E:\odoo14\odoo-14.0E\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "E:\odoo14\odoo-14.0E\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "E:\odoo14\odoo-14.0E\odoo\models.py", line 3893, in create
    fields[0].determine_inverse(batch_recs)
  File "E:\odoo14\odoo-14.0E\odoo\fields.py", line 1147, in determine_inverse
    getattr(records, self.inverse)()
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "E:\odoo14\odoo-14.0E\odoo\models.py", line 3682, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "E:\odoo14\odoo-14.0E\odoo\models.py", line 1250, in _validate_fields
    check(self)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 411, in _check_xml
    )).with_traceback(e.__traceback__) from None
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 942, in postprocess
    postprocessor(node, name_manager, node_info)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 1066, in _postprocess_tag_search
    searchpanel[0], name_manager.Model._name, name_manager.validate, editable=False,
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 954, in postprocess
    validator(node, name_manager, node_info)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 1090, in _validate_tag_field
    self.handle_view_error(msg)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: 验证视图时出错：

字段"routing_id" 不存在于模型 "mrp.bom"中

View name: mrp.bom.select.superbar
Error context:
 view: ir.ui.view(1416,)
 xmlid: view_mrp_bom_filter_superbar
 view.model: mrp.bom
 view.parent: ir.ui.view(1289,)
 file: e:\odoo14\odoo-14.0e\myaddons\app_mrp_superbar\views\mrp_bom_views.xml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\odoo14\odoo-14.0E\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "E:\odoo14\odoo-14.0E\odoo\addons\web\controllers\main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "E:\odoo14\odoo-14.0E\odoo\addons\web\controllers\main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\odoo14\odoo-14.0E\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "E:\odoo14\odoo-14.0E\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "E:\odoo14\odoo-14.0E\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "E:\odoo14\odoo-14.0E\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "E:\odoo14\odoo-14.0E\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "E:\odoo14\odoo-14.0E\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "E:\odoo14\odoo-14.0E\odoo\modules\loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "E:\odoo14\odoo-14.0E\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "E:\odoo14\odoo-14.0E\odoo\tools\convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "E:\odoo14\odoo-14.0E\odoo\tools\convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "E:\odoo14\odoo-14.0E\odoo\tools\convert.py", line 719, in parse
    self._tag_root(de)
  File "E:\odoo14\odoo-14.0E\odoo\tools\convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\odoo14\odoo-14.0E\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing file:/e:/odoo14/odoo-14.0e/myaddons/app_mrp_superbar/views/mrp_bom_views.xml:4, near
<record model="ir.ui.view" id="view_mrp_bom_filter_superbar">
        <field name="name">mrp.bom.select.superbar</field>
        <field name="model">mrp.bom</field>
        <field name="inherit_id" ref="mrp.view_mrp_bom_filter"/>
        <field name="arch" type="xml">
            <xpath expr="//search" position="inside">
                <searchpanel>
                    <field name="company_id" groups="base.group_multi_company" icon="fa-building"/>
                    <field name="type"/>
                    <field name="routing_id" groups="mrp.group_mrp_routings"/>
                </searchpanel>
            </xpath>
        </field>
    </record>

**Comment by guohuadeng** [comment]
fixed
