### ISSUE TITLE
[11.0] Error when installing addons

### ISSUE THREAD

**Issue by bitsnaps** [guohuadeng/app-odoo#50]
Hello, 

I got an error when installing any of *superbar* addons on Odoo v11 CE.
Here is end of the error log:
```
2021-11-09 21:26:33,513 12191 ERROR fmpi odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/path/to/odoo/tools/convert.py", line 745, in parse
….
  File "/path/to/odoo/addons/base/ir/ir_ui_view.py", line 350, in _check_xml
    raise ValidationError(_('Invalid view definition'))
odoo.exceptions.ValidationError: ('Invalid view definition', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
…
  File "/path/to/odoo/addons/base/ir/ir_ui_view.py", line 350, in _check_xml
    raise ValidationError(_('Invalid view definition'))
odoo.tools.convert.ParseError: "Invalid view definition
None" while parsing /path/to/odoo/extra/sunpop/app_project_superbar/views/project_project_views.xml:4, near
<record model="ir.ui.view" id="app_view_project_project_filter">
    <field name="name">app.project.project.select</field>
    <field name="model">project.project</field>
    <field name="inherit_id" ref="project.view_project_project_filter"/>
    <field name="arch" type="xml">
      <xpath expr="//search" position="inside">
        <superbar view_mode="kanban,tree">
          <field name="company_id" groups="base.group_multi_company"/>
          <field name="user_id"/>
          <field name="partner_id" widget="ztree_search" parent_key="parent_id" level="0"/>
        </superbar>
      </xpath>
    </field>
  </record>
```
OS: Ubuntu 20.04

**Comment by guohuadeng** [comment]
pls follow the guide in description.

u must restart odoo after install.

**Comment by bitsnaps** [comment]
> pls follow the guide in description.
> 
> u must restart odoo after install.

We can't even install the addons, you can try it in Gitpod in this branch [sunpop](https://github.com/bitsnaps/odoo-gitpod/tree/sunpop) (just click on Gitpod button on README).
