### ISSUE TITLE
Error when applying change to system name

### ISSUE THREAD

**Issue by trixocom** [guohuadeng/app-odoo#51]
Module latest version as of today. just installed pristine Odoo13.
When trying to apply a change on any default value, like System Name from OdooApp to somethign else. we get this error.
8 INFO ? werkzeug: 201.213.198.80 - - [12/Nov/2021 19:00:12] "GET /web/static/src/xml/crash_manager.xml?debug=1636743612477 HTTP/1.0" 200 - - - -
2021-11-12 19:00:18,267 538 ERROR electroql odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 385, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 365, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-160>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/opt/odoo/addons/account/models/res_config_settings.py", line 156, in create
    return super(ResConfigSettings, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/models.py", line 3812, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 3972, in _create
    for other, data in zip(others, data_list)
  File "/opt/odoo/odoo/fields.py", line 2899, in create
    self.write_batch(record_values, True)
  File "/opt/odoo/odoo/fields.py", line 2925, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo/fields.py", line 3477, in write_real
    relation_set(recs._ids, command[2] if command[0] == 6 else ())
  File "/opt/odoo/odoo/fields.py", line 3449, in relation_set
    new_relation[x] = set(ys)
  File "/opt/odoo/odoo/tools/misc.py", line 1073, in __init__
    self._map = OrderedDict((elem, None) for elem in elems)
TypeError: 'NoneType' object is not iterable

**Comment by guohuadeng** [comment]
test and no issue in odoo 13
