### ISSUE TITLE
14.0 - app_sale_superbar error

### ISSUE THREAD

**Issue by whotopia** [guohuadeng/app-odoo#58]
When using app_sale_superbar I get the error:

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo-14.0-OCB/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo-14.0-OCB/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/addons/web/models/models.py", line 568, in search_panel_select_range
    comodel_records = Comodel.search_read(comodel_domain, field_names, limit=limit)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 4873, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 1712, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/addons/base/models/res_users.py", line 539, in _search
    return super(Users, self)._search(args, offset=offset, limit=limit, order=order, count=count,
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 4542, in _search
    query = self._where_calc(args)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 4298, in _where_calc
    return expression.expression(domain, self).query
  File "/home/odoo/src/odoo-14.0-OCB/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/home/odoo/src/odoo-14.0-OCB/odoo/osv/expression.py", line 668, in parse
    dom = HIERARCHY_FUNCS[operator](left, ids2, model)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/osv/expression.py", line 576, in parent_of_domain
    records = records[parent_name] - records.browse(parent_ids)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 5624, in __sub__
    raise TypeError("Mixing apples and oranges: %s - %s" % (self, other))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Mixing apples and oranges: res.partner(1,) - res.users(6,)
```

**Comment by guohuadeng** [comment]
do u install
app_web_superbar ?

if you add extra tag follow our description, you need to buy that app.
if not, sale bar also can use with normal odoo code.


----------------------------------

Ivan Deng

Mobile：+86 13925160800

***@***.***

Guangzhou odooAi Co.Ltd.

https://www.odooai.cn


Professional Odoo Development and Business implementation
________________________________
发件人: whotopia ***@***.***>
发送时间: 2023年10月13日 15:52
收件人: guohuadeng/app-odoo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [guohuadeng/app-odoo] 14.0 - app_sale_superbar error (Issue #58)


When using app_sale_superbar I get the error:

Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo-14.0-OCB/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo-14.0-OCB/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo-14.0-OCB/addons/web/models/models.py", line 568, in search_panel_select_range
    comodel_records = Comodel.search_read(comodel_domain, field_names, limit=limit)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 4873, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 1712, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/addons/base/models/res_users.py", line 539, in _search
    return super(Users, self)._search(args, offset=offset, limit=limit, order=order, count=count,
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 4542, in _search
    query = self._where_calc(args)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 4298, in _where_calc
    return expression.expression(domain, self).query
  File "/home/odoo/src/odoo-14.0-OCB/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/home/odoo/src/odoo-14.0-OCB/odoo/osv/expression.py", line 668, in parse
    dom = HIERARCHY_FUNCS[operator](left, ids2, model)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/osv/expression.py", line 576, in parent_of_domain
    records = records[parent_name] - records.browse(parent_ids)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/models.py", line 5624, in __sub__
    raise TypeError("Mixing apples and oranges: %s - %s" % (self, other))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Mixing apples and oranges: res.partner(1,) - res.users(6,)


―
