### ISSUE TITLE
Getting error in sending email in Odoo 17 when app_common module is installed. 

### ISSUE THREAD

**Issue by shreeramy** [guohuadeng/app-odoo#61]
Getting below error when the app_common module is installed and when try to send any email.

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1734, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1761, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1962, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/res_users.py", line 180, in action_reset_password
    return self._action_reset_password()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/res_users.py", line 224, in _action_reset_password
    account_created_template.send_mail(
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_template.py", line 672, in send_mail
    mail.send(raise_exception=raise_exception)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_mail.py", line 551, in send
    self.browse(batch_ids)._send(
TypeError: MailMail._send() got an unexpected keyword argument 'alias_domain_id'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
```

We are getting this error because the _send method is not overriden correctly in  app_common/models/mail_mail.py", Also the method send_mail in "app_common/models/ir_mail_server.py" 

Please override them as per odoo17 format.

Get in touch with me for any odoo related work on : https://wangoes.com/contact.html

**Comment by guohuadeng** [comment]
fixed
